"""initial schema

Revision ID: 9e1fb71dd014
Revises:
Create Date: 2026-07-15 05:57:13.294052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1fb71dd014'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_cache',
    sa.Column('job_category', sa.String(length=100), nullable=False),
    sa.Column('total_posts_30d', sa.Integer(), nullable=False),
    sa.Column('growth_slope', sa.Float(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('job_category')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('target_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('last_scraped_message_id', sa.Integer(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_name')
    )
    op.create_table('raw_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('telegram_message_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['target_channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'telegram_message_id')
    )
    op.create_table('extracted_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_message_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('skills_required', sa.Text(), nullable=True),
    sa.Column('post_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['raw_message_id'], ['raw_messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extracted_jobs')
    op.drop_table('raw_messages')
    op.drop_table('target_channels')
    op.drop_table('users')
    op.drop_table('analytics_cache')
    # ### end Alembic commands ###
